sudo: false

language: python

python:
  - "3.7.6"
  - "3.8"
  - "3.8.2"

env:
  - DJANGO="Django>=2.2,<3.0.0"
  - DJANGO="Django>=3.0.4,<3.0.5"

install:
  - pip install $DJANGO -e .[tests]
  - pip freeze

script:
  - pytest
